{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e8d0f846",
   "metadata": {},
   "outputs": [],
   "source": [
    "from build123d import *\n",
    "from bd_warehouse.gear import SpurGear\n",
    "import jupyter_cadquery\n",
    "import random\n",
    "\n",
    "fidget_spinner_disc_radius = 90 * MM / 2\n",
    "fidget_spinner_top_button_radius = fidget_spinner_disc_radius / 2\n",
    "num_numbers = 15\n",
    "def math_function(x):\n",
    "    \"\"\"4x\"\"\"\n",
    "    return 4*x\n",
    "input_numbers = random.sample(range(8, 32), num_numbers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "328bae79",
   "metadata": {},
   "outputs": [],
   "source": [
    "text_baseline_radius = fidget_spinner_disc_radius * 0.775\n",
    "tolerance = 0.0\n",
    "font_path=\"Hind-Bold.ttf\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06df8ea3",
   "metadata": {},
   "outputs": [],
   "source": [
    "with BuildPart() as fidget_spinner_button_top:\n",
    "    with BuildSketch() as s:\n",
    "        Circle(fidget_spinner_top_button_radius)\n",
    "    extrude(amount=2)\n",
    "    chamfer(\n",
    "        fidget_spinner_button_top.edges()\n",
    "        .filter_by(GeomType.CIRCLE)\n",
    "        .sort_by(SortBy.RADIUS)\n",
    "        .sort_by(Axis.Z)[0],\n",
    "        angle=45,\n",
    "        length=0.5,\n",
    "    )\n",
    "\n",
    "    top_face = fidget_spinner_button_top.faces().sort_by(Axis.Z)[-1]\n",
    "    with BuildSketch(top_face) as s:\n",
    "        bearing_bore_radius = (8 - tolerance) / 2\n",
    "        Circle(bearing_bore_radius)\n",
    "    extrude(amount=4)\n",
    "    chamfer(\n",
    "        fidget_spinner_button_top.edges()\n",
    "        .filter_by(GeomType.CIRCLE)\n",
    "        .sort_by(SortBy.RADIUS)\n",
    "        .sort_by(Axis.Z)[-1],\n",
    "        angle=45,\n",
    "        length=0.25,\n",
    "    )\n",
    "\n",
    "    with BuildSketch(top_face) as s:\n",
    "        bearing_bore_case_radius = 12 / 2\n",
    "        Circle(bearing_bore_case_radius)\n",
    "    extrude(amount=1)\n",
    "\n",
    "    bottom_face = fidget_spinner_button_top.faces().sort_by(Axis.Z)[0]\n",
    "    with BuildSketch(bottom_face) as fidget_spinner_button_text:\n",
    "        with Locations((0, -0.53*fidget_spinner_top_button_radius)):\n",
    "            Text(\n",
    "                math_function.__doc__,\n",
    "                font_size=fidget_spinner_top_button_radius * 0.4,\n",
    "                font_style=FontStyle.BOLD,\n",
    "                font_path=font_path\n",
    "            )\n",
    "    extrude(amount=-0.4, mode=Mode.SUBTRACT)\n",
    "    extrude(\n",
    "        to_extrude=(\n",
    "            import_svg(\"arrow.svg\")[0]\n",
    "            .translate((-24, -24))\n",
    "            .scale(fidget_spinner_top_button_radius*0.02)\n",
    "            .rotate(Axis.Z, 180)\n",
    "            .translate((0, -0.53*fidget_spinner_top_button_radius))\n",
    "        ),\n",
    "        amount=0.4,\n",
    "        mode=Mode.SUBTRACT,\n",
    "    )\n",
    "\n",
    "    export_step(fidget_spinner_button_top.part, \"fidget_spinner_button_top.step\")\n",
    "fidget_spinner_button_top.part"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6d9cc4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "with BuildPart() as fidget_spinner_disc:\n",
    "    gear = SpurGear(\n",
    "        module=fidget_spinner_disc_radius*2/num_numbers,\n",
    "        tooth_count=num_numbers,\n",
    "        pressure_angle=18,\n",
    "        root_fillet=0.25 * MM,\n",
    "        thickness=2.5 * MM,\n",
    "        addendum=0,\n",
    "    )\n",
    "\n",
    "    # Gear is very slow to generate. Uncomment this section to use a disc as a placeholder while debugging, and comment out the gear code above.\n",
    "    # with BuildPart() as placeholder_disc:\n",
    "    #     with BuildSketch() as placeholder_circle:\n",
    "    #         Circle(fidget_spinner_disc_radius)\n",
    "    #     extrude(amount=2.5 * MM)\n",
    "    # gear = placeholder_disc.part\n",
    "\n",
    "    fidget_spinner_disc.part = fidget_spinner_disc.part + gear\n",
    "    fillet(\n",
    "        fidget_spinner_disc.faces().sort_by(Axis.Z)[-1].edges(),\n",
    "        radius=1 * MM,\n",
    "    )\n",
    "    chamfer(\n",
    "        fidget_spinner_disc.faces().sort_by(Axis.Z)[0].edges(),\n",
    "        angle=45,\n",
    "        length=0.9 * MM,\n",
    "    )\n",
    "\n",
    "    with BuildSketch() as center_hole:\n",
    "        Circle((22 * MM + tolerance) / 2)\n",
    "    extrude(amount=6 * MM, mode=Mode.SUBTRACT, both=True)\n",
    "    fillet(\n",
    "        fidget_spinner_disc.faces()\n",
    "        .sort_by(Axis.Z)[-1]\n",
    "        .edges()\n",
    "        .filter_by(GeomType.CIRCLE),\n",
    "        radius=0.25 * MM,\n",
    "    )\n",
    "\n",
    "    top_face_of_disc = fidget_spinner_disc.faces().sort_by(Axis.Z)[-1]\n",
    "    bottom_face_of_disc = fidget_spinner_disc.faces().sort_by(Axis.Z)[0]\n",
    "    with BuildSketch(top_face_of_disc) as numbers:\n",
    "        for index, number in enumerate(input_numbers):\n",
    "            with PolarLocations(\n",
    "                text_baseline_radius,\n",
    "                1,\n",
    "                -index * 360 / num_numbers + 90,\n",
    "                360,\n",
    "                rotate=True,\n",
    "            ):\n",
    "                Text(\n",
    "                    str(number),\n",
    "                    font_size=text_baseline_radius * 0.2,\n",
    "                    font_style=FontStyle.BOLD,\n",
    "                    rotation=-90,\n",
    "                    font_path=font_path,\n",
    "                )\n",
    "    extrude(amount=0.2)\n",
    "\n",
    "    with BuildSketch(bottom_face_of_disc) as answers:\n",
    "        for index, number in enumerate(input_numbers):\n",
    "            with PolarLocations(\n",
    "                text_baseline_radius, 1, index * 360 / num_numbers - 90, 360, rotate=True\n",
    "            ):\n",
    "                Text(\n",
    "                    str(math_function(number)),\n",
    "                    font_size=text_baseline_radius * 0.2,\n",
    "                    font_style=FontStyle.BOLD,\n",
    "                    rotation=90,\n",
    "                    font_path=font_path,\n",
    "                )\n",
    "    extrude(amount=-0.4, mode=Mode.SUBTRACT)\n",
    "export_step(fidget_spinner_disc.part, 'fidget_spinner_disc.step')\n",
    "fidget_spinner_disc.part"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b282875d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ideas for other operators\n",
    "operators = [\n",
    "    \"add\",\n",
    "    \"subtract\",\n",
    "    \"multiply\",\n",
    "    \"divide\",\n",
    "    \"percentage\",\n",
    "    \"power\",\n",
    "    \"root\",\n",
    "    \"triangle_angle_difference\",\n",
    "    \"pythoragoras\",\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a56b112d",
   "metadata": {
    "lines_to_next_cell": 2
   },
   "outputs": [],
   "source": [
    "\n"
   ]
  }
 ],
 "metadata": {
  "jupytext": {
   "cell_metadata_filter": "-all",
   "main_language": "python",
   "notebook_metadata_filter": "-all"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
